#pragma once

constexpr int INDICES_PER_FACE { 6 };
constexpr int POSITION_VALUES_PER_VERTEX { 3 };
constexpr int VALUES_PER_VERTEX { 6 }; 
constexpr int VALUES_PER_FACE { INDICES_PER_FACE * VALUES_PER_VERTEX };
constexpr int POSITIONAL_VALUES_PER_FACE { INDICES_PER_FACE * POSITION_VALUES_PER_VERTEX };
